// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Metadata;
using Oracle.EntityFrameworkCore.Metadata;
using esquire.Models.Fusion;

#pragma warning disable 219, 612, 618
#nullable enable

namespace esquire.Models.Compiled
{
    internal partial class PerAllAssignmentsMEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType? baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "esquire.Models.Fusion.PerAllAssignmentsM",
                typeof(PerAllAssignmentsM),
                baseEntityType);

            var actionCode = runtimeEntityType.AddProperty(
                "ActionCode",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ActionCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ActionCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            actionCode.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            actionCode.AddAnnotation("Relational:ColumnName", "ACTION_CODE");

            var actionOccurrenceId = runtimeEntityType.AddProperty(
                "ActionOccurrenceId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ActionOccurrenceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ActionOccurrenceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            actionOccurrenceId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            actionOccurrenceId.AddAnnotation("Relational:ColumnName", "ACTION_OCCURRENCE_ID");
            actionOccurrenceId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var allowAsgOverrideFlag = runtimeEntityType.AddProperty(
                "AllowAsgOverrideFlag",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("AllowAsgOverrideFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<AllowAsgOverrideFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            allowAsgOverrideFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            allowAsgOverrideFlag.AddAnnotation("Relational:ColumnName", "ALLOW_ASG_OVERRIDE_FLAG");

            var applicantRank = runtimeEntityType.AddProperty(
                "ApplicantRank",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ApplicantRank", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ApplicantRank>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            applicantRank.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            applicantRank.AddAnnotation("Relational:ColumnName", "APPLICANT_RANK");

            var assignmentId = runtimeEntityType.AddProperty(
                "AssignmentId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("AssignmentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<AssignmentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            assignmentId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            assignmentId.AddAnnotation("Relational:ColumnName", "ASSIGNMENT_ID");
            assignmentId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var assignmentName = runtimeEntityType.AddProperty(
                "AssignmentName",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("AssignmentName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<AssignmentName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            assignmentName.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            assignmentName.AddAnnotation("Relational:ColumnName", "ASSIGNMENT_NAME");

            var assignmentNumber = runtimeEntityType.AddProperty(
                "AssignmentNumber",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("AssignmentNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<AssignmentNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            assignmentNumber.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            assignmentNumber.AddAnnotation("Relational:ColumnName", "ASSIGNMENT_NUMBER");

            var assignmentSequence = runtimeEntityType.AddProperty(
                "AssignmentSequence",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("AssignmentSequence", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<AssignmentSequence>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            assignmentSequence.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            assignmentSequence.AddAnnotation("Relational:ColumnName", "ASSIGNMENT_SEQUENCE");
            assignmentSequence.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var assignmentStatusType = runtimeEntityType.AddProperty(
                "AssignmentStatusType",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("AssignmentStatusType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<AssignmentStatusType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            assignmentStatusType.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            assignmentStatusType.AddAnnotation("Relational:ColumnName", "ASSIGNMENT_STATUS_TYPE");

            var assignmentStatusTypeId = runtimeEntityType.AddProperty(
                "AssignmentStatusTypeId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("AssignmentStatusTypeId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<AssignmentStatusTypeId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            assignmentStatusTypeId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            assignmentStatusTypeId.AddAnnotation("Relational:ColumnName", "ASSIGNMENT_STATUS_TYPE_ID");
            assignmentStatusTypeId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var assignmentType = runtimeEntityType.AddProperty(
                "AssignmentType",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("AssignmentType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<AssignmentType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            assignmentType.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            assignmentType.AddAnnotation("Relational:ColumnName", "ASSIGNMENT_TYPE");

            var autoEndFlag = runtimeEntityType.AddProperty(
                "AutoEndFlag",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("AutoEndFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<AutoEndFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            autoEndFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            autoEndFlag.AddAnnotation("Relational:ColumnName", "AUTO_END_FLAG");

            var bargainingUnitCode = runtimeEntityType.AddProperty(
                "BargainingUnitCode",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("BargainingUnitCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<BargainingUnitCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            bargainingUnitCode.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            bargainingUnitCode.AddAnnotation("Relational:ColumnName", "BARGAINING_UNIT_CODE");

            var billingTitle = runtimeEntityType.AddProperty(
                "BillingTitle",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("BillingTitle", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<BillingTitle>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            billingTitle.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            billingTitle.AddAnnotation("Relational:ColumnName", "BILLING_TITLE");

            var businessGroupId = runtimeEntityType.AddProperty(
                "BusinessGroupId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("BusinessGroupId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<BusinessGroupId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            businessGroupId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            businessGroupId.AddAnnotation("Relational:ColumnName", "BUSINESS_GROUP_ID");
            businessGroupId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var businessUnitId = runtimeEntityType.AddProperty(
                "BusinessUnitId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("BusinessUnitId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<BusinessUnitId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            businessUnitId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            businessUnitId.AddAnnotation("Relational:ColumnName", "BUSINESS_UNIT_ID");
            businessUnitId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var cagrGradeDefId = runtimeEntityType.AddProperty(
                "CagrGradeDefId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("CagrGradeDefId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<CagrGradeDefId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            cagrGradeDefId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            cagrGradeDefId.AddAnnotation("Relational:ColumnName", "CAGR_GRADE_DEF_ID");
            cagrGradeDefId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var cagrIdFlexNum = runtimeEntityType.AddProperty(
                "CagrIdFlexNum",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("CagrIdFlexNum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<CagrIdFlexNum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            cagrIdFlexNum.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            cagrIdFlexNum.AddAnnotation("Relational:ColumnName", "CAGR_ID_FLEX_NUM");

            var categoryCode = runtimeEntityType.AddProperty(
                "CategoryCode",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("CategoryCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<CategoryCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            categoryCode.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            categoryCode.AddAnnotation("Relational:ColumnName", "CATEGORY_CODE");

            var collectiveAgreementId = runtimeEntityType.AddProperty(
                "CollectiveAgreementId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("CollectiveAgreementId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<CollectiveAgreementId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            collectiveAgreementId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            collectiveAgreementId.AddAnnotation("Relational:ColumnName", "COLLECTIVE_AGREEMENT_ID");
            collectiveAgreementId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var contractId = runtimeEntityType.AddProperty(
                "ContractId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ContractId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ContractId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            contractId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            contractId.AddAnnotation("Relational:ColumnName", "CONTRACT_ID");
            contractId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var createdBy = runtimeEntityType.AddProperty(
                "CreatedBy",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("CreatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<CreatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            createdBy.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            createdBy.AddAnnotation("Relational:ColumnName", "CREATED_BY");

            var creationDate = runtimeEntityType.AddProperty(
                "CreationDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("CreationDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<CreationDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            creationDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            creationDate.AddAnnotation("Relational:ColumnName", "CREATION_DATE");
            creationDate.AddAnnotation("Relational:ColumnType", "DATE");

            var dateProbationEnd = runtimeEntityType.AddProperty(
                "DateProbationEnd",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("DateProbationEnd", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<DateProbationEnd>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            dateProbationEnd.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            dateProbationEnd.AddAnnotation("Relational:ColumnName", "DATE_PROBATION_END");

            var defaultCodeCombId = runtimeEntityType.AddProperty(
                "DefaultCodeCombId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("DefaultCodeCombId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<DefaultCodeCombId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            defaultCodeCombId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            defaultCodeCombId.AddAnnotation("Relational:ColumnName", "DEFAULT_CODE_COMB_ID");
            defaultCodeCombId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var dutiesType = runtimeEntityType.AddProperty(
                "DutiesType",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("DutiesType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<DutiesType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            dutiesType.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            dutiesType.AddAnnotation("Relational:ColumnName", "DUTIES_TYPE");

            var effectiveEndDate = runtimeEntityType.AddProperty(
                "EffectiveEndDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("EffectiveEndDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<EffectiveEndDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            effectiveEndDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            effectiveEndDate.AddAnnotation("Relational:ColumnName", "EFFECTIVE_END_DATE");
            effectiveEndDate.AddAnnotation("Relational:ColumnType", "DATE");

            var effectiveLatestChange = runtimeEntityType.AddProperty(
                "EffectiveLatestChange",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("EffectiveLatestChange", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<EffectiveLatestChange>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            effectiveLatestChange.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            effectiveLatestChange.AddAnnotation("Relational:ColumnName", "EFFECTIVE_LATEST_CHANGE");

            var effectiveSequence = runtimeEntityType.AddProperty(
                "EffectiveSequence",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("EffectiveSequence", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<EffectiveSequence>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            effectiveSequence.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            effectiveSequence.AddAnnotation("Relational:ColumnName", "EFFECTIVE_SEQUENCE");
            effectiveSequence.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var effectiveStartDate = runtimeEntityType.AddProperty(
                "EffectiveStartDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("EffectiveStartDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<EffectiveStartDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            effectiveStartDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            effectiveStartDate.AddAnnotation("Relational:ColumnName", "EFFECTIVE_START_DATE");
            effectiveStartDate.AddAnnotation("Relational:ColumnType", "DATE");

            var employeeCategory = runtimeEntityType.AddProperty(
                "EmployeeCategory",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("EmployeeCategory", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<EmployeeCategory>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            employeeCategory.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            employeeCategory.AddAnnotation("Relational:ColumnName", "EMPLOYEE_CATEGORY");

            var employmentCategory = runtimeEntityType.AddProperty(
                "EmploymentCategory",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("EmploymentCategory", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<EmploymentCategory>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            employmentCategory.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            employmentCategory.AddAnnotation("Relational:ColumnName", "EMPLOYMENT_CATEGORY");

            var establishmentId = runtimeEntityType.AddProperty(
                "EstablishmentId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("EstablishmentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<EstablishmentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            establishmentId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            establishmentId.AddAnnotation("Relational:ColumnName", "ESTABLISHMENT_ID");
            establishmentId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var expenseCheckAddress = runtimeEntityType.AddProperty(
                "ExpenseCheckAddress",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ExpenseCheckAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ExpenseCheckAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            expenseCheckAddress.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            expenseCheckAddress.AddAnnotation("Relational:ColumnName", "EXPENSE_CHECK_ADDRESS");

            var freezeStartDate = runtimeEntityType.AddProperty(
                "FreezeStartDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("FreezeStartDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<FreezeStartDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            freezeStartDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            freezeStartDate.AddAnnotation("Relational:ColumnName", "FREEZE_START_DATE");
            freezeStartDate.AddAnnotation("Relational:ColumnType", "DATE");

            var freezeUntilDate = runtimeEntityType.AddProperty(
                "FreezeUntilDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("FreezeUntilDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<FreezeUntilDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            freezeUntilDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            freezeUntilDate.AddAnnotation("Relational:ColumnName", "FREEZE_UNTIL_DATE");
            freezeUntilDate.AddAnnotation("Relational:ColumnType", "DATE");

            var frequency = runtimeEntityType.AddProperty(
                "Frequency",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("Frequency", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<Frequency>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            frequency.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            frequency.AddAnnotation("Relational:ColumnName", "FREQUENCY");

            var fullPartTime = runtimeEntityType.AddProperty(
                "FullPartTime",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("FullPartTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<FullPartTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            fullPartTime.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            fullPartTime.AddAnnotation("Relational:ColumnName", "FULL_PART_TIME");

            var gradeId = runtimeEntityType.AddProperty(
                "GradeId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("GradeId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<GradeId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            gradeId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            gradeId.AddAnnotation("Relational:ColumnName", "GRADE_ID");
            gradeId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var gradeLadderPgmId = runtimeEntityType.AddProperty(
                "GradeLadderPgmId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("GradeLadderPgmId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<GradeLadderPgmId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            gradeLadderPgmId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            gradeLadderPgmId.AddAnnotation("Relational:ColumnName", "GRADE_LADDER_PGM_ID");
            gradeLadderPgmId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var gspEligibilityFlag = runtimeEntityType.AddProperty(
                "GspEligibilityFlag",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("GspEligibilityFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<GspEligibilityFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            gspEligibilityFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            gspEligibilityFlag.AddAnnotation("Relational:ColumnName", "GSP_ELIGIBILITY_FLAG");

            var hourlySalariedCode = runtimeEntityType.AddProperty(
                "HourlySalariedCode",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("HourlySalariedCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<HourlySalariedCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            hourlySalariedCode.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            hourlySalariedCode.AddAnnotation("Relational:ColumnName", "HOURLY_SALARIED_CODE");

            var idFlexNum = runtimeEntityType.AddProperty(
                "IdFlexNum",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("IdFlexNum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<IdFlexNum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            idFlexNum.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            idFlexNum.AddAnnotation("Relational:ColumnName", "ID_FLEX_NUM");

            var internalBuilding = runtimeEntityType.AddProperty(
                "InternalBuilding",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("InternalBuilding", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<InternalBuilding>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            internalBuilding.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            internalBuilding.AddAnnotation("Relational:ColumnName", "INTERNAL_BUILDING");

            var internalFloor = runtimeEntityType.AddProperty(
                "InternalFloor",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("InternalFloor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<InternalFloor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            internalFloor.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            internalFloor.AddAnnotation("Relational:ColumnName", "INTERNAL_FLOOR");

            var internalLocation = runtimeEntityType.AddProperty(
                "InternalLocation",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("InternalLocation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<InternalLocation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            internalLocation.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            internalLocation.AddAnnotation("Relational:ColumnName", "INTERNAL_LOCATION");

            var internalMailstop = runtimeEntityType.AddProperty(
                "InternalMailstop",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("InternalMailstop", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<InternalMailstop>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            internalMailstop.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            internalMailstop.AddAnnotation("Relational:ColumnName", "INTERNAL_MAILSTOP");

            var internalOfficeNumber = runtimeEntityType.AddProperty(
                "InternalOfficeNumber",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("InternalOfficeNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<InternalOfficeNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            internalOfficeNumber.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            internalOfficeNumber.AddAnnotation("Relational:ColumnName", "INTERNAL_OFFICE_NUMBER");

            var jobId = runtimeEntityType.AddProperty(
                "JobId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("JobId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<JobId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            jobId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            jobId.AddAnnotation("Relational:ColumnName", "JOB_ID");
            jobId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var jobPostSourceName = runtimeEntityType.AddProperty(
                "JobPostSourceName",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("JobPostSourceName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<JobPostSourceName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            jobPostSourceName.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            jobPostSourceName.AddAnnotation("Relational:ColumnName", "JOB_POST_SOURCE_NAME");

            var labourUnionMemberFlag = runtimeEntityType.AddProperty(
                "LabourUnionMemberFlag",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("LabourUnionMemberFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<LabourUnionMemberFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            labourUnionMemberFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            labourUnionMemberFlag.AddAnnotation("Relational:ColumnName", "LABOUR_UNION_MEMBER_FLAG");

            var lastUpdateDate = runtimeEntityType.AddProperty(
                "LastUpdateDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("LastUpdateDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<LastUpdateDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastUpdateDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            lastUpdateDate.AddAnnotation("Relational:ColumnName", "LAST_UPDATE_DATE");
            lastUpdateDate.AddAnnotation("Relational:ColumnType", "DATE");

            var lastUpdateLogin = runtimeEntityType.AddProperty(
                "LastUpdateLogin",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("LastUpdateLogin", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<LastUpdateLogin>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            lastUpdateLogin.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            lastUpdateLogin.AddAnnotation("Relational:ColumnName", "LAST_UPDATE_LOGIN");

            var lastUpdatedBy = runtimeEntityType.AddProperty(
                "LastUpdatedBy",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("LastUpdatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<LastUpdatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            lastUpdatedBy.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            lastUpdatedBy.AddAnnotation("Relational:ColumnName", "LAST_UPDATED_BY");

            var legalEntityId = runtimeEntityType.AddProperty(
                "LegalEntityId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("LegalEntityId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<LegalEntityId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            legalEntityId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            legalEntityId.AddAnnotation("Relational:ColumnName", "LEGAL_ENTITY_ID");
            legalEntityId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var legislationCode = runtimeEntityType.AddProperty(
                "LegislationCode",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("LegislationCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<LegislationCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            legislationCode.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            legislationCode.AddAnnotation("Relational:ColumnName", "LEGISLATION_CODE");

            var linkageType = runtimeEntityType.AddProperty(
                "LinkageType",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("LinkageType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<LinkageType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            linkageType.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            linkageType.AddAnnotation("Relational:ColumnName", "LINKAGE_TYPE");

            var locationId = runtimeEntityType.AddProperty(
                "LocationId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("LocationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<LocationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            locationId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            locationId.AddAnnotation("Relational:ColumnName", "LOCATION_ID");
            locationId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var managerFlag = runtimeEntityType.AddProperty(
                "ManagerFlag",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ManagerFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ManagerFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            managerFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            managerFlag.AddAnnotation("Relational:ColumnName", "MANAGER_FLAG");

            var normalHours = runtimeEntityType.AddProperty(
                "NormalHours",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("NormalHours", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<NormalHours>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            normalHours.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            normalHours.AddAnnotation("Relational:ColumnName", "NORMAL_HOURS");

            var noticePeriod = runtimeEntityType.AddProperty(
                "NoticePeriod",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("NoticePeriod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<NoticePeriod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            noticePeriod.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            noticePeriod.AddAnnotation("Relational:ColumnName", "NOTICE_PERIOD");

            var noticePeriodUom = runtimeEntityType.AddProperty(
                "NoticePeriodUom",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("NoticePeriodUom", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<NoticePeriodUom>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            noticePeriodUom.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            noticePeriodUom.AddAnnotation("Relational:ColumnName", "NOTICE_PERIOD_UOM");

            var objectVersionNumber = runtimeEntityType.AddProperty(
                "ObjectVersionNumber",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ObjectVersionNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ObjectVersionNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            objectVersionNumber.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            objectVersionNumber.AddAnnotation("Relational:ColumnName", "OBJECT_VERSION_NUMBER");
            objectVersionNumber.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var organizationId = runtimeEntityType.AddProperty(
                "OrganizationId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("OrganizationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<OrganizationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            organizationId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            organizationId.AddAnnotation("Relational:ColumnName", "ORGANIZATION_ID");
            organizationId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var overtimePeriod = runtimeEntityType.AddProperty(
                "OvertimePeriod",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("OvertimePeriod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<OvertimePeriod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            overtimePeriod.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            overtimePeriod.AddAnnotation("Relational:ColumnName", "OVERTIME_PERIOD");

            var parentAssignmentId = runtimeEntityType.AddProperty(
                "ParentAssignmentId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ParentAssignmentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ParentAssignmentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            parentAssignmentId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            parentAssignmentId.AddAnnotation("Relational:ColumnName", "PARENT_ASSIGNMENT_ID");
            parentAssignmentId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var peopleGroupId = runtimeEntityType.AddProperty(
                "PeopleGroupId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PeopleGroupId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PeopleGroupId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            peopleGroupId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            peopleGroupId.AddAnnotation("Relational:ColumnName", "PEOPLE_GROUP_ID");
            peopleGroupId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var periodOfServiceId = runtimeEntityType.AddProperty(
                "PeriodOfServiceId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PeriodOfServiceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PeriodOfServiceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            periodOfServiceId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            periodOfServiceId.AddAnnotation("Relational:ColumnName", "PERIOD_OF_SERVICE_ID");
            periodOfServiceId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var permanentTemporaryFlag = runtimeEntityType.AddProperty(
                "PermanentTemporaryFlag",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PermanentTemporaryFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PermanentTemporaryFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            permanentTemporaryFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            permanentTemporaryFlag.AddAnnotation("Relational:ColumnName", "PERMANENT_TEMPORARY_FLAG");

            var personId = runtimeEntityType.AddProperty(
                "PersonId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PersonId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PersonId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            personId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            personId.AddAnnotation("Relational:ColumnName", "PERSON_ID");
            personId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var personReferredById = runtimeEntityType.AddProperty(
                "PersonReferredById",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PersonReferredById", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PersonReferredById>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            personReferredById.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            personReferredById.AddAnnotation("Relational:ColumnName", "PERSON_REFERRED_BY_ID");
            personReferredById.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var personTypeId = runtimeEntityType.AddProperty(
                "PersonTypeId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PersonTypeId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PersonTypeId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            personTypeId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            personTypeId.AddAnnotation("Relational:ColumnName", "PERSON_TYPE_ID");
            personTypeId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var poHeaderId = runtimeEntityType.AddProperty(
                "PoHeaderId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PoHeaderId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PoHeaderId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            poHeaderId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            poHeaderId.AddAnnotation("Relational:ColumnName", "PO_HEADER_ID");
            poHeaderId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var poLineId = runtimeEntityType.AddProperty(
                "PoLineId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PoLineId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PoLineId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            poLineId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            poLineId.AddAnnotation("Relational:ColumnName", "PO_LINE_ID");
            poLineId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var positionId = runtimeEntityType.AddProperty(
                "PositionId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PositionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PositionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            positionId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            positionId.AddAnnotation("Relational:ColumnName", "POSITION_ID");
            positionId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var positionOverrideFlag = runtimeEntityType.AddProperty(
                "PositionOverrideFlag",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PositionOverrideFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PositionOverrideFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            positionOverrideFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            positionOverrideFlag.AddAnnotation("Relational:ColumnName", "POSITION_OVERRIDE_FLAG");

            var postingContentId = runtimeEntityType.AddProperty(
                "PostingContentId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PostingContentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PostingContentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            postingContentId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            postingContentId.AddAnnotation("Relational:ColumnName", "POSTING_CONTENT_ID");
            postingContentId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var primaryAssignmentFlag = runtimeEntityType.AddProperty(
                "PrimaryAssignmentFlag",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PrimaryAssignmentFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PrimaryAssignmentFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            primaryAssignmentFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            primaryAssignmentFlag.AddAnnotation("Relational:ColumnName", "PRIMARY_ASSIGNMENT_FLAG");

            var primaryFlag = runtimeEntityType.AddProperty(
                "PrimaryFlag",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PrimaryFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PrimaryFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            primaryFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            primaryFlag.AddAnnotation("Relational:ColumnName", "PRIMARY_FLAG");

            var primaryWorkRelationFlag = runtimeEntityType.AddProperty(
                "PrimaryWorkRelationFlag",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PrimaryWorkRelationFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PrimaryWorkRelationFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            primaryWorkRelationFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            primaryWorkRelationFlag.AddAnnotation("Relational:ColumnName", "PRIMARY_WORK_RELATION_FLAG");

            var primaryWorkTermsFlag = runtimeEntityType.AddProperty(
                "PrimaryWorkTermsFlag",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("PrimaryWorkTermsFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<PrimaryWorkTermsFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            primaryWorkTermsFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            primaryWorkTermsFlag.AddAnnotation("Relational:ColumnName", "PRIMARY_WORK_TERMS_FLAG");

            var probationPeriod = runtimeEntityType.AddProperty(
                "ProbationPeriod",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ProbationPeriod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ProbationPeriod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            probationPeriod.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            probationPeriod.AddAnnotation("Relational:ColumnName", "PROBATION_PERIOD");

            var probationUnit = runtimeEntityType.AddProperty(
                "ProbationUnit",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ProbationUnit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ProbationUnit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            probationUnit.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            probationUnit.AddAnnotation("Relational:ColumnName", "PROBATION_UNIT");

            var projectTitle = runtimeEntityType.AddProperty(
                "ProjectTitle",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ProjectTitle", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ProjectTitle>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            projectTitle.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            projectTitle.AddAnnotation("Relational:ColumnName", "PROJECT_TITLE");

            var projectedAssignmentEnd = runtimeEntityType.AddProperty(
                "ProjectedAssignmentEnd",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ProjectedAssignmentEnd", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ProjectedAssignmentEnd>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            projectedAssignmentEnd.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            projectedAssignmentEnd.AddAnnotation("Relational:ColumnName", "PROJECTED_ASSIGNMENT_END");

            var projectedStartDate = runtimeEntityType.AddProperty(
                "ProjectedStartDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ProjectedStartDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ProjectedStartDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            projectedStartDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            projectedStartDate.AddAnnotation("Relational:ColumnName", "PROJECTED_START_DATE");
            projectedStartDate.AddAnnotation("Relational:ColumnType", "DATE");

            var proposedWorkerType = runtimeEntityType.AddProperty(
                "ProposedWorkerType",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ProposedWorkerType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ProposedWorkerType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            proposedWorkerType.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            proposedWorkerType.AddAnnotation("Relational:ColumnName", "PROPOSED_WORKER_TYPE");

            var reasonCode = runtimeEntityType.AddProperty(
                "ReasonCode",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("ReasonCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<ReasonCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            reasonCode.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            reasonCode.AddAnnotation("Relational:ColumnName", "REASON_CODE");

            var recordCreator = runtimeEntityType.AddProperty(
                "RecordCreator",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("RecordCreator", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<RecordCreator>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            recordCreator.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            recordCreator.AddAnnotation("Relational:ColumnName", "RECORD_CREATOR");

            var recruiterId = runtimeEntityType.AddProperty(
                "RecruiterId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("RecruiterId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<RecruiterId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            recruiterId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            recruiterId.AddAnnotation("Relational:ColumnName", "RECRUITER_ID");
            recruiterId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var recruitmentActivityId = runtimeEntityType.AddProperty(
                "RecruitmentActivityId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("RecruitmentActivityId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<RecruitmentActivityId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            recruitmentActivityId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            recruitmentActivityId.AddAnnotation("Relational:ColumnName", "RECRUITMENT_ACTIVITY_ID");
            recruitmentActivityId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var retirementAge = runtimeEntityType.AddProperty(
                "RetirementAge",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("RetirementAge", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<RetirementAge>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            retirementAge.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            retirementAge.AddAnnotation("Relational:ColumnName", "RETIREMENT_AGE");

            var retirementDate = runtimeEntityType.AddProperty(
                "RetirementDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("RetirementDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<RetirementDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            retirementDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            retirementDate.AddAnnotation("Relational:ColumnName", "RETIREMENT_DATE");
            retirementDate.AddAnnotation("Relational:ColumnType", "DATE");

            var salReviewPeriod = runtimeEntityType.AddProperty(
                "SalReviewPeriod",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("SalReviewPeriod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<SalReviewPeriod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            salReviewPeriod.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            salReviewPeriod.AddAnnotation("Relational:ColumnName", "SAL_REVIEW_PERIOD");

            var salReviewPeriodFrequency = runtimeEntityType.AddProperty(
                "SalReviewPeriodFrequency",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("SalReviewPeriodFrequency", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<SalReviewPeriodFrequency>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            salReviewPeriodFrequency.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            salReviewPeriodFrequency.AddAnnotation("Relational:ColumnName", "SAL_REVIEW_PERIOD_FREQUENCY");

            var seniorityBasis = runtimeEntityType.AddProperty(
                "SeniorityBasis",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("SeniorityBasis", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<SeniorityBasis>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            seniorityBasis.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            seniorityBasis.AddAnnotation("Relational:ColumnName", "SENIORITY_BASIS");

            var setOfBooksId = runtimeEntityType.AddProperty(
                "SetOfBooksId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("SetOfBooksId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<SetOfBooksId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            setOfBooksId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            setOfBooksId.AddAnnotation("Relational:ColumnName", "SET_OF_BOOKS_ID");
            setOfBooksId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var softCodingKeyflexId = runtimeEntityType.AddProperty(
                "SoftCodingKeyflexId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("SoftCodingKeyflexId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<SoftCodingKeyflexId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            softCodingKeyflexId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            softCodingKeyflexId.AddAnnotation("Relational:ColumnName", "SOFT_CODING_KEYFLEX_ID");
            softCodingKeyflexId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var sourceAssignmentId = runtimeEntityType.AddProperty(
                "SourceAssignmentId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("SourceAssignmentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<SourceAssignmentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sourceAssignmentId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            sourceAssignmentId.AddAnnotation("Relational:ColumnName", "SOURCE_ASSIGNMENT_ID");
            sourceAssignmentId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var sourceOrganizationId = runtimeEntityType.AddProperty(
                "SourceOrganizationId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("SourceOrganizationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<SourceOrganizationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sourceOrganizationId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            sourceOrganizationId.AddAnnotation("Relational:ColumnName", "SOURCE_ORGANIZATION_ID");
            sourceOrganizationId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var sourceType = runtimeEntityType.AddProperty(
                "SourceType",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("SourceType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<SourceType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            sourceType.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            sourceType.AddAnnotation("Relational:ColumnName", "SOURCE_TYPE");

            var specialCeilingStepId = runtimeEntityType.AddProperty(
                "SpecialCeilingStepId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("SpecialCeilingStepId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<SpecialCeilingStepId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            specialCeilingStepId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            specialCeilingStepId.AddAnnotation("Relational:ColumnName", "SPECIAL_CEILING_STEP_ID");
            specialCeilingStepId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var stepEntryDate = runtimeEntityType.AddProperty(
                "StepEntryDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("StepEntryDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<StepEntryDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            stepEntryDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            stepEntryDate.AddAnnotation("Relational:ColumnName", "STEP_ENTRY_DATE");
            stepEntryDate.AddAnnotation("Relational:ColumnType", "DATE");

            var systemPersonType = runtimeEntityType.AddProperty(
                "SystemPersonType",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("SystemPersonType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<SystemPersonType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            systemPersonType.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            systemPersonType.AddAnnotation("Relational:ColumnName", "SYSTEM_PERSON_TYPE");

            var taxAddressId = runtimeEntityType.AddProperty(
                "TaxAddressId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("TaxAddressId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<TaxAddressId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            taxAddressId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            taxAddressId.AddAnnotation("Relational:ColumnName", "TAX_ADDRESS_ID");
            taxAddressId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var timeNormalFinish = runtimeEntityType.AddProperty(
                "TimeNormalFinish",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("TimeNormalFinish", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<TimeNormalFinish>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            timeNormalFinish.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            timeNormalFinish.AddAnnotation("Relational:ColumnName", "TIME_NORMAL_FINISH");

            var timeNormalStart = runtimeEntityType.AddProperty(
                "TimeNormalStart",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("TimeNormalStart", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<TimeNormalStart>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            timeNormalStart.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            timeNormalStart.AddAnnotation("Relational:ColumnName", "TIME_NORMAL_START");

            var unionId = runtimeEntityType.AddProperty(
                "UnionId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("UnionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<UnionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            unionId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            unionId.AddAnnotation("Relational:ColumnName", "UNION_ID");
            unionId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var vacancyId = runtimeEntityType.AddProperty(
                "VacancyId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("VacancyId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<VacancyId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            vacancyId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            vacancyId.AddAnnotation("Relational:ColumnName", "VACANCY_ID");
            vacancyId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var vendorAssignmentNumber = runtimeEntityType.AddProperty(
                "VendorAssignmentNumber",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("VendorAssignmentNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<VendorAssignmentNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            vendorAssignmentNumber.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            vendorAssignmentNumber.AddAnnotation("Relational:ColumnName", "VENDOR_ASSIGNMENT_NUMBER");

            var vendorEmployeeNumber = runtimeEntityType.AddProperty(
                "VendorEmployeeNumber",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("VendorEmployeeNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<VendorEmployeeNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            vendorEmployeeNumber.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            vendorEmployeeNumber.AddAnnotation("Relational:ColumnName", "VENDOR_EMPLOYEE_NUMBER");

            var vendorId = runtimeEntityType.AddProperty(
                "VendorId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("VendorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<VendorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            vendorId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            vendorId.AddAnnotation("Relational:ColumnName", "VENDOR_ID");
            vendorId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var vendorSiteId = runtimeEntityType.AddProperty(
                "VendorSiteId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("VendorSiteId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<VendorSiteId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            vendorSiteId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            vendorSiteId.AddAnnotation("Relational:ColumnName", "VENDOR_SITE_ID");
            vendorSiteId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var workAtHome = runtimeEntityType.AddProperty(
                "WorkAtHome",
                typeof(string),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("WorkAtHome", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<WorkAtHome>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            workAtHome.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            workAtHome.AddAnnotation("Relational:ColumnName", "WORK_AT_HOME");

            var workTermsAssignmentId = runtimeEntityType.AddProperty(
                "WorkTermsAssignmentId",
                typeof(decimal?),
                propertyInfo: typeof(PerAllAssignmentsM).GetProperty("WorkTermsAssignmentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerAllAssignmentsM).GetField("<WorkTermsAssignmentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            workTermsAssignmentId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            workTermsAssignmentId.AddAnnotation("Relational:ColumnName", "WORK_TERMS_ASSIGNMENT_ID");
            workTermsAssignmentId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "FUSION");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "PER_ALL_ASSIGNMENTS_M");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
