// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Metadata;
using Oracle.EntityFrameworkCore.Metadata;
using esquire.Models.Fusion;

#pragma warning disable 219, 612, 618
#nullable enable

namespace esquire.Models.Compiled
{
    internal partial class FndCompiledMenuFunctionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType? baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "esquire.Models.Fusion.FndCompiledMenuFunction",
                typeof(FndCompiledMenuFunction),
                baseEntityType);

            var changeSinceLastRefresh = runtimeEntityType.AddProperty(
                "ChangeSinceLastRefresh",
                typeof(string),
                propertyInfo: typeof(FndCompiledMenuFunction).GetProperty("ChangeSinceLastRefresh", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndCompiledMenuFunction).GetField("<ChangeSinceLastRefresh>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            changeSinceLastRefresh.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            changeSinceLastRefresh.AddAnnotation("Relational:ColumnName", "CHANGE_SINCE_LAST_REFRESH");

            var enterpriseId = runtimeEntityType.AddProperty(
                "EnterpriseId",
                typeof(decimal?),
                propertyInfo: typeof(FndCompiledMenuFunction).GetProperty("EnterpriseId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndCompiledMenuFunction).GetField("<EnterpriseId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            enterpriseId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            enterpriseId.AddAnnotation("Relational:ColumnName", "ENTERPRISE_ID");
            enterpriseId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var flag = runtimeEntityType.AddProperty(
                "Flag",
                typeof(string),
                propertyInfo: typeof(FndCompiledMenuFunction).GetProperty("Flag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndCompiledMenuFunction).GetField("<Flag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            flag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            flag.AddAnnotation("Relational:ColumnName", "FLAG");

            var functionId = runtimeEntityType.AddProperty(
                "FunctionId",
                typeof(decimal?),
                propertyInfo: typeof(FndCompiledMenuFunction).GetProperty("FunctionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndCompiledMenuFunction).GetField("<FunctionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            functionId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            functionId.AddAnnotation("Relational:ColumnName", "FUNCTION_ID");
            functionId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var menuId = runtimeEntityType.AddProperty(
                "MenuId",
                typeof(decimal?),
                propertyInfo: typeof(FndCompiledMenuFunction).GetProperty("MenuId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndCompiledMenuFunction).GetField("<MenuId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            menuId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            menuId.AddAnnotation("Relational:ColumnName", "MENU_ID");
            menuId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var sandboxId = runtimeEntityType.AddProperty(
                "SandboxId",
                typeof(decimal?),
                propertyInfo: typeof(FndCompiledMenuFunction).GetProperty("SandboxId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndCompiledMenuFunction).GetField("<SandboxId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sandboxId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            sandboxId.AddAnnotation("Relational:ColumnName", "SANDBOX_ID");
            sandboxId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "FUSION");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "FND_COMPILED_MENU_FUNCTIONS");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
