// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Metadata;
using Oracle.EntityFrameworkCore.Metadata;
using esquire.Models.Fusion;

#pragma warning disable 219, 612, 618
#nullable enable

namespace esquire.Models.Compiled
{
    internal partial class FndGrantEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType? baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "esquire.Models.Fusion.FndGrant",
                typeof(FndGrant),
                baseEntityType);

            var changeSinceLastRefresh = runtimeEntityType.AddProperty(
                "ChangeSinceLastRefresh",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("ChangeSinceLastRefresh", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<ChangeSinceLastRefresh>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            changeSinceLastRefresh.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            changeSinceLastRefresh.AddAnnotation("Relational:ColumnName", "CHANGE_SINCE_LAST_REFRESH");

            var compileFlag = runtimeEntityType.AddProperty(
                "CompileFlag",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("CompileFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<CompileFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            compileFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            compileFlag.AddAnnotation("Relational:ColumnName", "COMPILE_FLAG");

            var contextName = runtimeEntityType.AddProperty(
                "ContextName",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("ContextName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<ContextName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            contextName.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            contextName.AddAnnotation("Relational:ColumnName", "CONTEXT_NAME");

            var contextValue = runtimeEntityType.AddProperty(
                "ContextValue",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("ContextValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<ContextValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            contextValue.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            contextValue.AddAnnotation("Relational:ColumnName", "CONTEXT_VALUE");

            var createdBy = runtimeEntityType.AddProperty(
                "CreatedBy",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("CreatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<CreatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            createdBy.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            createdBy.AddAnnotation("Relational:ColumnName", "CREATED_BY");

            var creationDate = runtimeEntityType.AddProperty(
                "CreationDate",
                typeof(DateTime?),
                propertyInfo: typeof(FndGrant).GetProperty("CreationDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<CreationDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            creationDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            creationDate.AddAnnotation("Relational:ColumnName", "CREATION_DATE");
            creationDate.AddAnnotation("Relational:ColumnType", "DATE");

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 550,
                unicode: false);
            description.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            description.AddAnnotation("Relational:ColumnName", "DESCRIPTION");

            var endDate = runtimeEntityType.AddProperty(
                "EndDate",
                typeof(DateTime?),
                propertyInfo: typeof(FndGrant).GetProperty("EndDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<EndDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            endDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            endDate.AddAnnotation("Relational:ColumnName", "END_DATE");
            endDate.AddAnnotation("Relational:ColumnType", "DATE");

            var enterpriseId = runtimeEntityType.AddProperty(
                "EnterpriseId",
                typeof(decimal?),
                propertyInfo: typeof(FndGrant).GetProperty("EnterpriseId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<EnterpriseId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            enterpriseId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            enterpriseId.AddAnnotation("Relational:ColumnName", "ENTERPRISE_ID");
            enterpriseId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var grantGuid = runtimeEntityType.AddProperty(
                "GrantGuid",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("GrantGuid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<GrantGuid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            grantGuid.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            grantGuid.AddAnnotation("Relational:ColumnName", "GRANT_GUID");

            var grantType = runtimeEntityType.AddProperty(
                "GrantType",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("GrantType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<GrantType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            grantType.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            grantType.AddAnnotation("Relational:ColumnName", "GRANT_TYPE");

            var granteeKey = runtimeEntityType.AddProperty(
                "GranteeKey",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("GranteeKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<GranteeKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            granteeKey.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            granteeKey.AddAnnotation("Relational:ColumnName", "GRANTEE_KEY");

            var granteeType = runtimeEntityType.AddProperty(
                "GranteeType",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("GranteeType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<GranteeType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            granteeType.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            granteeType.AddAnnotation("Relational:ColumnName", "GRANTEE_TYPE");

            var instancePk1Value = runtimeEntityType.AddProperty(
                "InstancePk1Value",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("InstancePk1Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<InstancePk1Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            instancePk1Value.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            instancePk1Value.AddAnnotation("Relational:ColumnName", "INSTANCE_PK1_VALUE");

            var instancePk2Value = runtimeEntityType.AddProperty(
                "InstancePk2Value",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("InstancePk2Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<InstancePk2Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            instancePk2Value.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            instancePk2Value.AddAnnotation("Relational:ColumnName", "INSTANCE_PK2_VALUE");

            var instancePk3Value = runtimeEntityType.AddProperty(
                "InstancePk3Value",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("InstancePk3Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<InstancePk3Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            instancePk3Value.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            instancePk3Value.AddAnnotation("Relational:ColumnName", "INSTANCE_PK3_VALUE");

            var instancePk4Value = runtimeEntityType.AddProperty(
                "InstancePk4Value",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("InstancePk4Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<InstancePk4Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            instancePk4Value.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            instancePk4Value.AddAnnotation("Relational:ColumnName", "INSTANCE_PK4_VALUE");

            var instancePk5Value = runtimeEntityType.AddProperty(
                "InstancePk5Value",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("InstancePk5Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<InstancePk5Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            instancePk5Value.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            instancePk5Value.AddAnnotation("Relational:ColumnName", "INSTANCE_PK5_VALUE");

            var instanceSetId = runtimeEntityType.AddProperty(
                "InstanceSetId",
                typeof(decimal?),
                propertyInfo: typeof(FndGrant).GetProperty("InstanceSetId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<InstanceSetId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            instanceSetId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            instanceSetId.AddAnnotation("Relational:ColumnName", "INSTANCE_SET_ID");
            instanceSetId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var instanceType = runtimeEntityType.AddProperty(
                "InstanceType",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("InstanceType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<InstanceType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            instanceType.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            instanceType.AddAnnotation("Relational:ColumnName", "INSTANCE_TYPE");

            var isEnterpriseRole = runtimeEntityType.AddProperty(
                "IsEnterpriseRole",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("IsEnterpriseRole", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<IsEnterpriseRole>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            isEnterpriseRole.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            isEnterpriseRole.AddAnnotation("Relational:ColumnName", "IS_ENTERPRISE_ROLE");

            var j2eeAppName = runtimeEntityType.AddProperty(
                "J2eeAppName",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("J2eeAppName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<J2eeAppName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            j2eeAppName.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            j2eeAppName.AddAnnotation("Relational:ColumnName", "J2EE_APP_NAME");

            var lastUpdateDate = runtimeEntityType.AddProperty(
                "LastUpdateDate",
                typeof(DateTime?),
                propertyInfo: typeof(FndGrant).GetProperty("LastUpdateDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<LastUpdateDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastUpdateDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            lastUpdateDate.AddAnnotation("Relational:ColumnName", "LAST_UPDATE_DATE");
            lastUpdateDate.AddAnnotation("Relational:ColumnType", "DATE");

            var lastUpdateLogin = runtimeEntityType.AddProperty(
                "LastUpdateLogin",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("LastUpdateLogin", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<LastUpdateLogin>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            lastUpdateLogin.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            lastUpdateLogin.AddAnnotation("Relational:ColumnName", "LAST_UPDATE_LOGIN");

            var lastUpdatedBy = runtimeEntityType.AddProperty(
                "LastUpdatedBy",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("LastUpdatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<LastUpdatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            lastUpdatedBy.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            lastUpdatedBy.AddAnnotation("Relational:ColumnName", "LAST_UPDATED_BY");

            var menuId = runtimeEntityType.AddProperty(
                "MenuId",
                typeof(decimal?),
                propertyInfo: typeof(FndGrant).GetProperty("MenuId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<MenuId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            menuId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            menuId.AddAnnotation("Relational:ColumnName", "MENU_ID");
            menuId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var moduleId = runtimeEntityType.AddProperty(
                "ModuleId",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("ModuleId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<ModuleId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            moduleId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            moduleId.AddAnnotation("Relational:ColumnName", "MODULE_ID");

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            name.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            name.AddAnnotation("Relational:ColumnName", "NAME");

            var objectId = runtimeEntityType.AddProperty(
                "ObjectId",
                typeof(decimal?),
                propertyInfo: typeof(FndGrant).GetProperty("ObjectId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<ObjectId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            objectId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            objectId.AddAnnotation("Relational:ColumnName", "OBJECT_ID");
            objectId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var parameter1 = runtimeEntityType.AddProperty(
                "Parameter1",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Parameter1", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Parameter1>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            parameter1.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            parameter1.AddAnnotation("Relational:ColumnName", "PARAMETER1");

            var parameter10 = runtimeEntityType.AddProperty(
                "Parameter10",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Parameter10", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Parameter10>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            parameter10.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            parameter10.AddAnnotation("Relational:ColumnName", "PARAMETER10");

            var parameter2 = runtimeEntityType.AddProperty(
                "Parameter2",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Parameter2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Parameter2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            parameter2.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            parameter2.AddAnnotation("Relational:ColumnName", "PARAMETER2");

            var parameter3 = runtimeEntityType.AddProperty(
                "Parameter3",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Parameter3", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Parameter3>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            parameter3.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            parameter3.AddAnnotation("Relational:ColumnName", "PARAMETER3");

            var parameter4 = runtimeEntityType.AddProperty(
                "Parameter4",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Parameter4", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Parameter4>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            parameter4.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            parameter4.AddAnnotation("Relational:ColumnName", "PARAMETER4");

            var parameter5 = runtimeEntityType.AddProperty(
                "Parameter5",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Parameter5", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Parameter5>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            parameter5.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            parameter5.AddAnnotation("Relational:ColumnName", "PARAMETER5");

            var parameter6 = runtimeEntityType.AddProperty(
                "Parameter6",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Parameter6", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Parameter6>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            parameter6.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            parameter6.AddAnnotation("Relational:ColumnName", "PARAMETER6");

            var parameter7 = runtimeEntityType.AddProperty(
                "Parameter7",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Parameter7", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Parameter7>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            parameter7.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            parameter7.AddAnnotation("Relational:ColumnName", "PARAMETER7");

            var parameter8 = runtimeEntityType.AddProperty(
                "Parameter8",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Parameter8", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Parameter8>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            parameter8.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            parameter8.AddAnnotation("Relational:ColumnName", "PARAMETER8");

            var parameter9 = runtimeEntityType.AddProperty(
                "Parameter9",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("Parameter9", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<Parameter9>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            parameter9.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            parameter9.AddAnnotation("Relational:ColumnName", "PARAMETER9");

            var programName = runtimeEntityType.AddProperty(
                "ProgramName",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("ProgramName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<ProgramName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            programName.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            programName.AddAnnotation("Relational:ColumnName", "PROGRAM_NAME");

            var programTag = runtimeEntityType.AddProperty(
                "ProgramTag",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("ProgramTag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<ProgramTag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            programTag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            programTag.AddAnnotation("Relational:ColumnName", "PROGRAM_TAG");

            var roleName = runtimeEntityType.AddProperty(
                "RoleName",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("RoleName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<RoleName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            roleName.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            roleName.AddAnnotation("Relational:ColumnName", "ROLE_NAME");

            var roleNameSpace = runtimeEntityType.AddProperty(
                "RoleNameSpace",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("RoleNameSpace", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<RoleNameSpace>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            roleNameSpace.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            roleNameSpace.AddAnnotation("Relational:ColumnName", "ROLE_NAME_SPACE");

            var sandboxId = runtimeEntityType.AddProperty(
                "SandboxId",
                typeof(decimal?),
                propertyInfo: typeof(FndGrant).GetProperty("SandboxId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<SandboxId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sandboxId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            sandboxId.AddAnnotation("Relational:ColumnName", "SANDBOX_ID");
            sandboxId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var seedDataSource = runtimeEntityType.AddProperty(
                "SeedDataSource",
                typeof(string),
                propertyInfo: typeof(FndGrant).GetProperty("SeedDataSource", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<SeedDataSource>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 150,
                unicode: false);
            seedDataSource.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            seedDataSource.AddAnnotation("Relational:ColumnName", "SEED_DATA_SOURCE");

            var startDate = runtimeEntityType.AddProperty(
                "StartDate",
                typeof(DateTime?),
                propertyInfo: typeof(FndGrant).GetProperty("StartDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FndGrant).GetField("<StartDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            startDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            startDate.AddAnnotation("Relational:ColumnName", "START_DATE");
            startDate.AddAnnotation("Relational:ColumnType", "DATE");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "FUSION");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "FND_GRANTS");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
