// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Metadata;
using Oracle.EntityFrameworkCore.Metadata;
using esquire.Models.Fusion;

#pragma warning disable 219, 612, 618
#nullable enable

namespace esquire.Models.Compiled
{
    internal partial class GlCodeCombinationEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType? baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "esquire.Models.Fusion.GlCodeCombination",
                typeof(GlCodeCombination),
                baseEntityType);

            var alternateCodeCombinationId = runtimeEntityType.AddProperty(
                "AlternateCodeCombinationId",
                typeof(decimal?),
                propertyInfo: typeof(GlCodeCombination).GetProperty("AlternateCodeCombinationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GlCodeCombination).GetField("<AlternateCodeCombinationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            alternateCodeCombinationId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            alternateCodeCombinationId.AddAnnotation("Relational:ColumnName", "ALTERNATE_CODE_COMBINATION_ID");
            alternateCodeCombinationId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var codeCombinationId = runtimeEntityType.AddProperty(
                "CodeCombinationId",
                typeof(decimal?),
                propertyInfo: typeof(GlCodeCombination).GetProperty("CodeCombinationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GlCodeCombination).GetField("<CodeCombinationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            codeCombinationId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            codeCombinationId.AddAnnotation("Relational:ColumnName", "CODE_COMBINATION_ID");
            codeCombinationId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var createdByUserId = runtimeEntityType.AddProperty(
                "CreatedByUserId",
                typeof(decimal?),
                propertyInfo: typeof(GlCodeCombination).GetProperty("CreatedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GlCodeCombination).GetField("<CreatedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            createdByUserId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            createdByUserId.AddAnnotation("Relational:ColumnName", "CREATED_BY_USER_ID");
            createdByUserId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var creationDate = runtimeEntityType.AddProperty(
                "CreationDate",
                typeof(DateTime?),
                propertyInfo: typeof(GlCodeCombination).GetProperty("CreationDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GlCodeCombination).GetField("<CreationDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            creationDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            creationDate.AddAnnotation("Relational:ColumnName", "CREATION_DATE");
            creationDate.AddAnnotation("Relational:ColumnType", "DATE");

            var endDateActive = runtimeEntityType.AddProperty(
                "EndDateActive",
                typeof(string),
                propertyInfo: typeof(GlCodeCombination).GetProperty("EndDateActive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GlCodeCombination).GetField("<EndDateActive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            endDateActive.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            endDateActive.AddAnnotation("Relational:ColumnName", "END_DATE_ACTIVE");

            var lastUpdateDate = runtimeEntityType.AddProperty(
                "LastUpdateDate",
                typeof(DateTime?),
                propertyInfo: typeof(GlCodeCombination).GetProperty("LastUpdateDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GlCodeCombination).GetField("<LastUpdateDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastUpdateDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            lastUpdateDate.AddAnnotation("Relational:ColumnName", "LAST_UPDATE_DATE");
            lastUpdateDate.AddAnnotation("Relational:ColumnType", "DATE");

            var lastUpdatedByUserId = runtimeEntityType.AddProperty(
                "LastUpdatedByUserId",
                typeof(decimal?),
                propertyInfo: typeof(GlCodeCombination).GetProperty("LastUpdatedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GlCodeCombination).GetField("<LastUpdatedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastUpdatedByUserId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            lastUpdatedByUserId.AddAnnotation("Relational:ColumnName", "LAST_UPDATED_BY_USER_ID");
            lastUpdatedByUserId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var pDateFrom = runtimeEntityType.AddProperty(
                "PDateFrom",
                typeof(DateTime?),
                propertyInfo: typeof(GlCodeCombination).GetProperty("PDateFrom", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GlCodeCombination).GetField("<PDateFrom>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            pDateFrom.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            pDateFrom.AddAnnotation("Relational:ColumnName", "_P_DATE_FROM");
            pDateFrom.AddAnnotation("Relational:ColumnType", "DATE");

            var pDateTo = runtimeEntityType.AddProperty(
                "PDateTo",
                typeof(DateTime?),
                propertyInfo: typeof(GlCodeCombination).GetProperty("PDateTo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GlCodeCombination).GetField("<PDateTo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            pDateTo.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            pDateTo.AddAnnotation("Relational:ColumnName", "_P_DATE_TO");
            pDateTo.AddAnnotation("Relational:ColumnType", "DATE");

            var revaluationId = runtimeEntityType.AddProperty(
                "RevaluationId",
                typeof(decimal?),
                propertyInfo: typeof(GlCodeCombination).GetProperty("RevaluationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GlCodeCombination).GetField("<RevaluationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            revaluationId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            revaluationId.AddAnnotation("Relational:ColumnName", "REVALUATION_ID");
            revaluationId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var startDateActive = runtimeEntityType.AddProperty(
                "StartDateActive",
                typeof(string),
                propertyInfo: typeof(GlCodeCombination).GetProperty("StartDateActive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GlCodeCombination).GetField("<StartDateActive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            startDateActive.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            startDateActive.AddAnnotation("Relational:ColumnName", "START_DATE_ACTIVE");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "FUSION");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "GL_CODE_COMBINATIONS");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
