// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Metadata;
using Oracle.EntityFrameworkCore.Metadata;
using esquire.Models.Fusion;

#pragma warning disable 219, 612, 618
#nullable enable

namespace esquire.Models.Compiled
{
    internal partial class PerLocationDetailsXEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType? baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "esquire.Models.Fusion.PerLocationDetailsX",
                typeof(PerLocationDetailsX),
                baseEntityType);

            var acLocationCode = runtimeEntityType.AddProperty(
                "AcLocationCode",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("AcLocationCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<AcLocationCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            acLocationCode.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            acLocationCode.AddAnnotation("Relational:ColumnName", "AC_LOCATION_CODE");

            var activeStatus = runtimeEntityType.AddProperty(
                "ActiveStatus",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("ActiveStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<ActiveStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            activeStatus.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            activeStatus.AddAnnotation("Relational:ColumnName", "ACTIVE_STATUS");

            var billToSiteFlag = runtimeEntityType.AddProperty(
                "BillToSiteFlag",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("BillToSiteFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<BillToSiteFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            billToSiteFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            billToSiteFlag.AddAnnotation("Relational:ColumnName", "BILL_TO_SITE_FLAG");

            var businessGroupId = runtimeEntityType.AddProperty(
                "BusinessGroupId",
                typeof(decimal?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("BusinessGroupId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<BusinessGroupId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            businessGroupId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            businessGroupId.AddAnnotation("Relational:ColumnName", "BUSINESS_GROUP_ID");
            businessGroupId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var createdBy = runtimeEntityType.AddProperty(
                "CreatedBy",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("CreatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<CreatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            createdBy.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            createdBy.AddAnnotation("Relational:ColumnName", "CREATED_BY");

            var creationDate = runtimeEntityType.AddProperty(
                "CreationDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("CreationDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<CreationDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            creationDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            creationDate.AddAnnotation("Relational:ColumnName", "CREATION_DATE");
            creationDate.AddAnnotation("Relational:ColumnType", "DATE");

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            description.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            description.AddAnnotation("Relational:ColumnName", "DESCRIPTION");

            var designatedReceiverId = runtimeEntityType.AddProperty(
                "DesignatedReceiverId",
                typeof(decimal?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("DesignatedReceiverId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<DesignatedReceiverId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            designatedReceiverId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            designatedReceiverId.AddAnnotation("Relational:ColumnName", "DESIGNATED_RECEIVER_ID");
            designatedReceiverId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var effectiveEndDate = runtimeEntityType.AddProperty(
                "EffectiveEndDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("EffectiveEndDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<EffectiveEndDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            effectiveEndDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            effectiveEndDate.AddAnnotation("Relational:ColumnName", "EFFECTIVE_END_DATE");
            effectiveEndDate.AddAnnotation("Relational:ColumnType", "DATE");

            var effectiveStartDate = runtimeEntityType.AddProperty(
                "EffectiveStartDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("EffectiveStartDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<EffectiveStartDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            effectiveStartDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            effectiveStartDate.AddAnnotation("Relational:ColumnName", "EFFECTIVE_START_DATE");
            effectiveStartDate.AddAnnotation("Relational:ColumnType", "DATE");

            var emailAddress = runtimeEntityType.AddProperty(
                "EmailAddress",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("EmailAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<EmailAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            emailAddress.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            emailAddress.AddAnnotation("Relational:ColumnName", "EMAIL_ADDRESS");

            var faxAreaCode2 = runtimeEntityType.AddProperty(
                "FaxAreaCode2",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("FaxAreaCode2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<FaxAreaCode2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            faxAreaCode2.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            faxAreaCode2.AddAnnotation("Relational:ColumnName", "FAX_AREA_CODE2");

            var faxCountryCode2 = runtimeEntityType.AddProperty(
                "FaxCountryCode2",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("FaxCountryCode2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<FaxCountryCode2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            faxCountryCode2.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            faxCountryCode2.AddAnnotation("Relational:ColumnName", "FAX_COUNTRY_CODE2");

            var faxExtension2 = runtimeEntityType.AddProperty(
                "FaxExtension2",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("FaxExtension2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<FaxExtension2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            faxExtension2.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            faxExtension2.AddAnnotation("Relational:ColumnName", "FAX_EXTENSION2");

            var faxSubscriberNum2 = runtimeEntityType.AddProperty(
                "FaxSubscriberNum2",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("FaxSubscriberNum2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<FaxSubscriberNum2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            faxSubscriberNum2.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            faxSubscriberNum2.AddAnnotation("Relational:ColumnName", "FAX_SUBSCRIBER_NUM2");

            var geoHierarchyNodeId = runtimeEntityType.AddProperty(
                "GeoHierarchyNodeId",
                typeof(decimal?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("GeoHierarchyNodeId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<GeoHierarchyNodeId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            geoHierarchyNodeId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            geoHierarchyNodeId.AddAnnotation("Relational:ColumnName", "GEO_HIERARCHY_NODE_ID");
            geoHierarchyNodeId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var geoHierarchyNodeValue = runtimeEntityType.AddProperty(
                "GeoHierarchyNodeValue",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("GeoHierarchyNodeValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<GeoHierarchyNodeValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            geoHierarchyNodeValue.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            geoHierarchyNodeValue.AddAnnotation("Relational:ColumnName", "GEO_HIERARCHY_NODE_VALUE");

            var inventoryOrganizationId = runtimeEntityType.AddProperty(
                "InventoryOrganizationId",
                typeof(decimal?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("InventoryOrganizationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<InventoryOrganizationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            inventoryOrganizationId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            inventoryOrganizationId.AddAnnotation("Relational:ColumnName", "INVENTORY_ORGANIZATION_ID");
            inventoryOrganizationId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var lastUpdateDate = runtimeEntityType.AddProperty(
                "LastUpdateDate",
                typeof(DateTime?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("LastUpdateDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<LastUpdateDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastUpdateDate.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            lastUpdateDate.AddAnnotation("Relational:ColumnName", "LAST_UPDATE_DATE");
            lastUpdateDate.AddAnnotation("Relational:ColumnType", "DATE");

            var lastUpdateLogin = runtimeEntityType.AddProperty(
                "LastUpdateLogin",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("LastUpdateLogin", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<LastUpdateLogin>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            lastUpdateLogin.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            lastUpdateLogin.AddAnnotation("Relational:ColumnName", "LAST_UPDATE_LOGIN");

            var lastUpdatedBy = runtimeEntityType.AddProperty(
                "LastUpdatedBy",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("LastUpdatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<LastUpdatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            lastUpdatedBy.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            lastUpdatedBy.AddAnnotation("Relational:ColumnName", "LAST_UPDATED_BY");

            var locationCode = runtimeEntityType.AddProperty(
                "LocationCode",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("LocationCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<LocationCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            locationCode.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            locationCode.AddAnnotation("Relational:ColumnName", "LOCATION_CODE");

            var locationDetailsId = runtimeEntityType.AddProperty(
                "LocationDetailsId",
                typeof(decimal?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("LocationDetailsId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<LocationDetailsId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            locationDetailsId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            locationDetailsId.AddAnnotation("Relational:ColumnName", "LOCATION_DETAILS_ID");
            locationDetailsId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var locationId = runtimeEntityType.AddProperty(
                "LocationId",
                typeof(decimal?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("LocationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<LocationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            locationId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            locationId.AddAnnotation("Relational:ColumnName", "LOCATION_ID");
            locationId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var locationName = runtimeEntityType.AddProperty(
                "LocationName",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("LocationName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<LocationName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            locationName.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            locationName.AddAnnotation("Relational:ColumnName", "LOCATION_NAME");

            var mainAddressId = runtimeEntityType.AddProperty(
                "MainAddressId",
                typeof(decimal?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("MainAddressId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<MainAddressId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            mainAddressId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            mainAddressId.AddAnnotation("Relational:ColumnName", "MAIN_ADDRESS_ID");
            mainAddressId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var mainphoneAreaCode1 = runtimeEntityType.AddProperty(
                "MainphoneAreaCode1",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("MainphoneAreaCode1", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<MainphoneAreaCode1>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            mainphoneAreaCode1.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            mainphoneAreaCode1.AddAnnotation("Relational:ColumnName", "MAINPHONE_AREA_CODE1");

            var mainphoneCountryCode1 = runtimeEntityType.AddProperty(
                "MainphoneCountryCode1",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("MainphoneCountryCode1", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<MainphoneCountryCode1>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            mainphoneCountryCode1.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            mainphoneCountryCode1.AddAnnotation("Relational:ColumnName", "MAINPHONE_COUNTRY_CODE1");

            var mainphoneExtension1 = runtimeEntityType.AddProperty(
                "MainphoneExtension1",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("MainphoneExtension1", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<MainphoneExtension1>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            mainphoneExtension1.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            mainphoneExtension1.AddAnnotation("Relational:ColumnName", "MAINPHONE_EXTENSION1");

            var mainphoneSubscriberNum1 = runtimeEntityType.AddProperty(
                "MainphoneSubscriberNum1",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("MainphoneSubscriberNum1", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<MainphoneSubscriberNum1>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            mainphoneSubscriberNum1.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            mainphoneSubscriberNum1.AddAnnotation("Relational:ColumnName", "MAINPHONE_SUBSCRIBER_NUM1");

            var objectVersionNumber = runtimeEntityType.AddProperty(
                "ObjectVersionNumber",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("ObjectVersionNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<ObjectVersionNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            objectVersionNumber.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            objectVersionNumber.AddAnnotation("Relational:ColumnName", "OBJECT_VERSION_NUMBER");

            var officeSiteFlag = runtimeEntityType.AddProperty(
                "OfficeSiteFlag",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("OfficeSiteFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<OfficeSiteFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            officeSiteFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            officeSiteFlag.AddAnnotation("Relational:ColumnName", "OFFICE_SITE_FLAG");

            var officialLanguageCode = runtimeEntityType.AddProperty(
                "OfficialLanguageCode",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("OfficialLanguageCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<OfficialLanguageCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            officialLanguageCode.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            officialLanguageCode.AddAnnotation("Relational:ColumnName", "OFFICIAL_LANGUAGE_CODE");

            var otherphoneAreaCode3 = runtimeEntityType.AddProperty(
                "OtherphoneAreaCode3",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("OtherphoneAreaCode3", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<OtherphoneAreaCode3>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            otherphoneAreaCode3.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            otherphoneAreaCode3.AddAnnotation("Relational:ColumnName", "OTHERPHONE_AREA_CODE3");

            var otherphoneCountryCode3 = runtimeEntityType.AddProperty(
                "OtherphoneCountryCode3",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("OtherphoneCountryCode3", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<OtherphoneCountryCode3>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            otherphoneCountryCode3.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            otherphoneCountryCode3.AddAnnotation("Relational:ColumnName", "OTHERPHONE_COUNTRY_CODE3");

            var otherphoneExtension3 = runtimeEntityType.AddProperty(
                "OtherphoneExtension3",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("OtherphoneExtension3", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<OtherphoneExtension3>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            otherphoneExtension3.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            otherphoneExtension3.AddAnnotation("Relational:ColumnName", "OTHERPHONE_EXTENSION3");

            var otherphoneSubscriberNum3 = runtimeEntityType.AddProperty(
                "OtherphoneSubscriberNum3",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("OtherphoneSubscriberNum3", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<OtherphoneSubscriberNum3>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            otherphoneSubscriberNum3.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            otherphoneSubscriberNum3.AddAnnotation("Relational:ColumnName", "OTHERPHONE_SUBSCRIBER_NUM3");

            var receivingSiteFlag = runtimeEntityType.AddProperty(
                "ReceivingSiteFlag",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("ReceivingSiteFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<ReceivingSiteFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            receivingSiteFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            receivingSiteFlag.AddAnnotation("Relational:ColumnName", "RECEIVING_SITE_FLAG");

            var shipToLocationId = runtimeEntityType.AddProperty(
                "ShipToLocationId",
                typeof(decimal?),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("ShipToLocationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<ShipToLocationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            shipToLocationId.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            shipToLocationId.AddAnnotation("Relational:ColumnName", "SHIP_TO_LOCATION_ID");
            shipToLocationId.AddAnnotation("Relational:ColumnType", "NUMBER(38)");

            var shipToSiteFlag = runtimeEntityType.AddProperty(
                "ShipToSiteFlag",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("ShipToSiteFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<ShipToSiteFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            shipToSiteFlag.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            shipToSiteFlag.AddAnnotation("Relational:ColumnName", "SHIP_TO_SITE_FLAG");

            var telephoneNumber1 = runtimeEntityType.AddProperty(
                "TelephoneNumber1",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("TelephoneNumber1", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<TelephoneNumber1>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            telephoneNumber1.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            telephoneNumber1.AddAnnotation("Relational:ColumnName", "TELEPHONE_NUMBER_1");

            var telephoneNumber2 = runtimeEntityType.AddProperty(
                "TelephoneNumber2",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("TelephoneNumber2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<TelephoneNumber2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            telephoneNumber2.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            telephoneNumber2.AddAnnotation("Relational:ColumnName", "TELEPHONE_NUMBER_2");

            var telephoneNumber3 = runtimeEntityType.AddProperty(
                "TelephoneNumber3",
                typeof(string),
                propertyInfo: typeof(PerLocationDetailsX).GetProperty("TelephoneNumber3", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerLocationDetailsX).GetField("<TelephoneNumber3>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50,
                unicode: false);
            telephoneNumber3.AddAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.None);
            telephoneNumber3.AddAnnotation("Relational:ColumnName", "TELEPHONE_NUMBER_3");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "FUSION");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "PER_LOCATION_DETAILS_X");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
